version: '3.8'

volumes:
  sql_data:

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: yerbowo_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: always

  web:
    image: wojtuchny/yerbowo-app:latest
    container_name: yerbowo-app
    build:
      context: .
      dockerfile: YerbowoBackend/Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - AZURE_KEYVAULT_URL=${AZURE_KEYVAULT_URL}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      
