trigger:
  branches:
    include:
      - "*"

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: dotnetSdkVersion
    value: '10.x'

stages:
- template: ../templates/backend.yml
  parameters:
    buildConfiguration: ${{ variables.buildConfiguration }}
    dotnetSdkVersion: ${{ variables.dotnetSdkVersion }}

- template: ../templates/frontend.yml

- template: ../templates/combine-artifacts.yml